### ISSUE TITLE
Panic on crafted input found by fuzzer

### ISSUE THREAD

**Issue by Shnatsel** [tirr-c/jxl-oxide#169]
Decoding the following file causes a panic: 
[crash-351112d496bdea0981dd3c35de0ac7fb9a389d1f.jxl.gz](https://github.com/tirr-c/jxl-oxide/files/13820038/crash-351112d496bdea0981dd3c35de0ac7fb9a389d1f.jxl.gz)

Backtrace:

```
thread '<unnamed>' panicked at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library/core/src/num/f32.rs:1498:9:
min > max, or either was NaN. min = inf, max = -inf
stack backtrace:
   0: rust_begin_unwind
             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library/core/src/panicking.rs:72:14
   2: core::f32::<impl f32>::clamp
             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library/core/src/num/f32.rs:1498:9
   3: jxl_render::features::upsampling::upsample_inner
             at /home/shnatsel/Code/jxl-oxide/crates/jxl-render/src/features/upsampling.rs:130:45
   4: jxl_render::features::upsampling::upsample
             at /home/shnatsel/Code/jxl-oxide/crates/jxl-render/src/features/upsampling.rs:47:14
   5: jxl_render::inner::upsample_color_channels::{{closure}}
             at /home/shnatsel/Code/jxl-oxide/crates/jxl-render/src/inner.rs:190:17
   6: tracing::span::Span::in_scope
             at /home/shnatsel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/span.rs:1102:9
   7: jxl_render::inner::upsample_color_channels
             at /home/shnatsel/Code/jxl-oxide/crates/jxl-render/src/inner.rs:188:9
   8: jxl_render::inner::render_frame
             at /home/shnatsel/Code/jxl-oxide/crates/jxl-render/src/inner.rs:126:5
   9: jxl_render::RenderContext::render_op::{{closure}}
             at /home/shnatsel/Code/jxl-oxide/crates/jxl-render/src/lib.rs:379:26
  10: jxl_render::state::FrameRenderHandle::run_with_image
             at /home/shnatsel/Code/jxl-oxide/crates/jxl-render/src/state.rs:113:33
  11: jxl_render::RenderContext::render_by_index
             at /home/shnatsel/Code/jxl-oxide/crates/jxl-render/src/lib.rs:504:9
  12: jxl_render::RenderContext::render_keyframe
             at /home/shnatsel/Code/jxl-oxide/crates/jxl-render/src/lib.rs:527:24
  13: jxl_oxide::JxlImage::render_frame_cropped
             at ./src/lib.rs:699:25
  14: jxl_oxide::JxlImage::render_frame
             at ./src/lib.rs:690:9
  15: decode::fuzz_decode
             at ./fuzz/fuzz_targets/decode.rs:25:21
  16: rust_fuzzer_test_input
             at /home/shnatsel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.7/src/lib.rs:224:17
  17: libfuzzer_sys::test_input_wrap::{{closure}}
             at /home/shnatsel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.7/src/lib.rs:61:9
  18: std::panicking::try::do_call
             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library/std/src/panicking.rs:552:40
  19: std::panicking::try
             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library/std/src/panicking.rs:516:19
  20: std::panic::catch_unwind
             at /rustc/89e2160c4ca5808657ed55392620ed1dbbce78d1/library/std/src/panic.rs:142:14
  21: LLVMFuzzerTestOneInput
             at /home/shnatsel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.7/src/lib.rs:59:22
  22: _ZN6fuzzer6Fuzzer15ExecuteCallbackEPKhm
             at /home/shnatsel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.7/libfuzzer/FuzzerLoop.cpp:612:15
  23: _ZN6fuzzer10RunOneTestEPNS_6FuzzerEPKcm
             at /home/shnatsel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.7/libfuzzer/FuzzerDriver.cpp:324:21
  24: _ZN6fuzzer12FuzzerDriverEPiPPPcPFiPKhmE
             at /home/shnatsel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.7/libfuzzer/FuzzerDriver.cpp:860:19
  25: main
             at /home/shnatsel/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libfuzzer-sys-0.4.7/libfuzzer/FuzzerMain.cpp:20:30
  26: <unknown>
  27: __libc_start_main
  28: _start
```

Found with `cargo fuzz`. Tested on commit b1115f987e2ca269ca903e6726e04a74db703438

**Comment by Shnatsel** [comment]
Still can be triggered on commit 37a074eb3cc16b63915f554928292527928a8c09 with this file: 
[crash-9ca585248fa8b3b936ecc97544da968b372eba6a.jxl.gz](https://github.com/tirr-c/jxl-oxide/files/13854356/crash-9ca585248fa8b3b936ecc97544da968b372eba6a.jxl.gz)

**Comment by Shnatsel** [comment]
Could you reopen this issue so that it doesn't get lost?

**Comment by tirr-c** [comment]
This should be fixed now.

I'll run the fuzzer before releasing 0.6. I hope this doesn't panic again...
